### PR TITLE
Indizen 2019 talks

### PR DESCRIPTION
**Pull request by newlawrence**
I've created the folders for the missing talks we've had at **Indizen** this year with their respective welcome presentations.

I've also added Francisco's April presentation. There are our last **Godot** talk and both @jgsogo lightning talks left.

### CODE REVIEW

**Comment by Manu343726** [comment]
There's a conflict with @jgsogo's #35 I think

**Comment by newlawrence** [comment]
You're right. Not sure what is best, for me to close this **PR** and rebase my changes to #35. Or wait for @jgsogo to merge his and then this.

**Comment by jgsogo** [comment]
Ok, mine is merged, I've created a PR to your branch with the changes https://github.com/newlawrence/Meetups/pull/1 Merge it and we are ready 💪

**Comment by newlawrence** [comment]
Ok, I messed up with the history a little bit, but it's fixed now, we are able to merge this branch.

**Comment by jgsogo** [comment]
Thanks a lot! Happy New Year!

**Pull request merged**
